#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# set root password
if [ -n "$ROOTPW" ]; then
    $ROOTCMD chpasswd --encrypted <<< "root:${ROOTPW}"
    ainsl /etc/ssh/sshd_config "^PermitRootLogin yes$"
fi
if [ -n "$username" ]; then
#    $ROOTCMD usermod -L root
    # enable sudo for user
    ainsl /etc/sudoers "$username   ALL=NOPASSWD: ALL"
    if [ ! -f $target/usr/bin/sudo ]; then
	echo "WARNING. Package sudo is not installed"
    fi
fi
if [ -n "$usernameansible" ]; then
    $ROOTCMD groupadd -g 10001 $usernameansible
    $ROOTCMD useradd -u 10001 -g 10001 -m $usernameansible
    # enable sudo for user
    ainsl /etc/sudoers "$usernameansible   ALL=NOPASSWD: ALL"
    if [ ! -f $target/usr/bin/sudo ]; then
	echo "WARNING. Package sudo is not installed"
    fi
fi

exit $error
