#!/bin/bash
error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code
$ROOTCMD rm -f /etc/network/interfaces
$ROOTCMD systemctl enable --now systemd-networkd
$ROOTCMD systemctl disable systemd-networkd-wait-online.service
$ROOTCMD mkdir -p /root/.ssh
$ROOTCMD mkdir -p /home/$username/.ssh
$ROOTCMD mkdir -p /home/$usernameansible/.ssh
$ROOTCMD chmod 700 /root/.ssh
$ROOTCMD chmod 700 /home/$username/.ssh
$ROOTCMD chmod 700 /home/$usernameansible/.ssh
$ROOTCMD touch /root/.ssh/authorized_keys
$ROOTCMD touch /home/$username/.ssh/authorized_keys
$ROOTCMD touch /home/$usernameansible/.ssh/authorized_keys
ainsl /root/.ssh/authorized_keys "$myrootkey"
ainsl /home/$username/.ssh/authorized_keys "$myuserkey"
ainsl /home/$usernameansible/.ssh/authorized_keys "$ansiblekey"

$ROOTCMD chown -R root:root /root/.ssh
$ROOTCMD chown -R $username:$username /home/$username/.ssh
$ROOTCMD chown -R $usernameansible:$usernameansible /home/$usernameansible/.ssh
$ROOTCMD chmod 600 /home/$username/.ssh/authorized_keys /root/.ssh/authorized_keys /home/$usernameansible/.ssh/authorized_keys

if [ -n "${REMOTENIC+x}" ] && [ -n "${REMOTEADDR+x}" ] && [ -n "${REMOTEGW+x}" ]
then
  cat <<EOF > $target/etc/systemd/network/00-init.network
[Match]
Name=$REMOTENIC
[Network]
Address=$REMOTEADDR
Gateway=$REMOTEGW
EOF
fi

$ROOTCMD chmod 644 /etc/systemd/network/00-init.network
