#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

$ROOTCMD systemctl disable corosync.service
$ROOTCMD systemctl disable pacemaker.service
$ROOTCMD systemctl disable timemaster.service

$ROOTCMD apt -y autoremove
