#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# add additional user account
if [ -n "$username" ]; then
    if ! $ROOTCMD getent passwd $username ; then
	$ROOTCMD adduser --disabled-password --gecos "$username user" $username
	$ROOTCMD usermod -p "$USERPW" $username
	userdir=$($ROOTCMD getent passwd "$username" | cut -d: -f6 )

	# disable xfce question about default or empty panel
	if [ -f $target/etc/xdg/xfce4/panel/default.xml ]; then
	    xfdir=$userdir/.config/xfce4/xfconf/xfce-perchannel-xml
	    if [ ! -d $target/$xfdir ]; then
		$ROOTCMD mkdir -p $xfdir
		$ROOTCMD cp /etc/xdg/xfce4/panel/default.xml $xfdir/xfce4-panel.xml
		# group name is the same as user name
		$ROOTCMD chown -R $username:$username $userdir/.config
	    fi
	fi

	for g in $groups; do
	    $ROOTCMD adduser $username $g
	done
    fi
fi

# set root password
if [ -n "$ROOTPW" ]; then
    $ROOTCMD chpasswd --encrypted <<< "root:${ROOTPW}"
    ainsl /etc/ssh/sshd_config "^PermitRootLogin yes$"
fi
if [ -n "$username" ]; then
#    $ROOTCMD usermod -L root
    # enable sudo for user
    ainsl /etc/sudoers "$username   ALL=NOPASSWD: ALL"
    if [ ! -f $target/usr/bin/sudo ]; then
	echo "WARNING. Package sudo is not installed"
    fi
fi
if [ -n "$usernameansible" ]; then
    $ROOTCMD groupadd -g 1005 $usernameansible
    $ROOTCMD useradd -u 1005 -g 1005 -m $usernameansible
    # enable sudo for ansible user with only needed rights
    ainsl /etc/sudoers "Defaults:$usernameansible !requiretty"
    ainsl /etc/sudoers "$usernameansible    ALL=NOPASSWD:EXEC:SETENV: /bin/sh"
    ainsl /etc/sudoers "$usernameansible    ALL=NOPASSWD: /usr/bin/rsync"
    if [ ! -f $target/usr/bin/sudo ]; then
	echo "WARNING. Package sudo is not installed"
    fi
fi

exit $error
