#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# Disable systemd's network interface name management.
# References:
#   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863385
#   https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

fcopy -M /etc/default/grub.d/20_efi_ipv6.cfg
$ROOTCMD update-grub
