#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

$ROOTCMD systemctl disable timemaster.service
$ROOTCMD systemctl disable tuned.service

$ROOTCMD apt -y autoremove
