#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code
shopt -s nullglob

BUILD_IMAGES_DIR="$FAI/files/opt/images"
LOCAL_IMAGES_DIR="/opt/images"

mkdir -p "$FAI_ROOT$LOCAL_IMAGES_DIR"

# Collect all images that have been saved to the build directory and load them
# in the guest local image storage.
# No need to parse the container_images.conf files again since the image
# generation script already does it and save the needed images in /opt/images.
for build_image_file in "$BUILD_IMAGES_DIR"/*; do
    image_name=$(basename "$build_image_file")
    echo "Loading container image $image_name"
    image_path="$LOCAL_IMAGES_DIR/$image_name"

    # We copy the image since chrooted podman does not have access to the
    # files outside its local filesystem.
    cp "$build_image_file" "$FAI_ROOT$image_path"
    $ROOTCMD podman load -i "$image_path"
    rm -f "$FAI_ROOT$image_path"

    # NOTE: the original image file is not removed since it will be later used
    # for SBOM generation
done
