#!/bin/bash

# do not use this if a menu will be presented
[ "$flag_menu" ] && exit 0

echo DEBIAN FAIBASE TRIXIE64 SEAPATH_COMMON SEAPATH_HOST

[ "$flag_german" ] && echo "GERMAN"
[ "$flag_french" ] && echo "FRENCH"
[ "$flag_cluster" ] && echo "SEAPATH_CLUSTER"
[ "$flag_raid" ] && [ "$flag_cluster" ] && echo "SEAPATH_RAID"
[ ! "$flag_raid" ] && [ ! "$flag_cluster" ] && echo "SEAPATH_CEPH_DISK"
[ "$flag_raid" ] && [ ! "$flag_cluster" ] && echo "SEAPATH_RAID_CEPH_DISK"
[ "$flag_raiddemo" ] && echo "SEAPATH_RAID SEAPATH_RAID_DEMO"
[ "$flag_ceph_disk" ] && echo "SEAPATH_CEPH_DISK"
[ "$flag_ceph_disk" ] && [ "$flag_raid" ] && echo "SEAPATH_RAID_CEPH_DISK"
[ "$flag_dbg" ] && echo "SEAPATH_DBG"
[ "$flag_kerberos" ] && echo "SEAPATH_KERBEROS"
[ "$flag_cockpit" ] && echo "SEAPATH_COCKPIT"

arch=$(uname -m)

if [ "$arch" == "aarch64" ]; then
    echo "SEAPATH_ARM64"
else
    echo "SEAPATH_AMD64"
fi

echo "USERCUSTOMIZATION"

exit 0
