#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

$ROOTCMD systemctl disable corosync.service
$ROOTCMD systemctl disable pacemaker.service
$ROOTCMD systemctl disable nginx.service

fcopy -m root,root,0755  /usr/local/bin/cephadm
for i in quay.io/ceph/ceph:v19.2.2 docker.io/library/registry:2
do
    registry=$(echo $i | cut -d'/' -f2)
    image=$(echo $i | cut -d'/' -f3 | sed s/://g)
    fcopy -M /opt/$registry"_"$image.tgz
done
fcopy -m root,root,0755 /firstboot.sh
fcopy -M /etc/systemd/system/firstboot.service
$ROOTCMD systemctl enable firstboot.service
