#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

$ROOTCMD systemctl disable corosync.service
$ROOTCMD systemctl disable pacemaker.service

for i in quay.io/ceph/ceph:v16 quay.io/ceph/ceph-grafana:8.3.5 quay.io/prometheus/prometheus:v2.33.4 quay.io/prometheus/node-exporter:v1.3.1 quay.io/prometheus/alertmanager:v0.23.0
do
    registry=$(echo $i | cut -d'/' -f2)
    image=$(echo $i | cut -d'/' -f3 | sed s/://g)
    fcopy -M /opt/$registry"_"$image.tgz
done
fcopy -m root,root,0755 /firstboot.sh
fcopy -M /etc/systemd/system/firstboot.service
$ROOTCMD systemctl enable firstboot.service
