#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

fcopy -m root,root,0755  /usr/local/bin/cephadm
# Copy container images tgz files to /opt
# Read container_images.conf from FAI files structure (ignore comments and empty lines)
CONTAINER_IMAGES_CONF="/var/lib/fai/config/files/etc/container_images.conf/SEAPATH_CLUSTER"
if [ -f "$CONTAINER_IMAGES_CONF" ]; then
    while IFS= read -r i || [ -n "$i" ]; do
        # Skip empty lines and comments
        [[ -z "$i" || "$i" =~ ^[[:space:]]*# ]] && continue
        # Trim whitespace
        i=$(echo "$i" | xargs)
        [[ -z "$i" ]] && continue
        
        registry=$(echo $i | cut -d'/' -f2)
        image=$(echo $i | cut -d'/' -f3 | sed s/://g)
        fcopy -M /opt/$registry"_"$image.tgz
    done < "$CONTAINER_IMAGES_CONF"
fi
fcopy -m root,root,0755 /firstboot.sh
fcopy -M /etc/systemd/system/firstboot.service
$ROOTCMD systemctl enable firstboot.service
