#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# Copy cephadm binary (specific to SEAPATH_CLUSTER)
# Note: Container images are handled by SEAPATH_COMMON/65-container-images script
fcopy -m root,root,0755  /usr/local/bin/cephadm

